---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpipam-v1
  namespace: umg
  labels:
    app: phpipam
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpipam
      version: v1
  template:
    metadata:
      labels:
        app: phpipam
        version: v1
    spec:
      serviceAccountName: phpipam
      containers:
      - name: phpipam
        image: docker-registry.umusic.com/networking/phpipam:v1.4.2-umg-1.0
        resources:
          limits:
            memory: 4096Mi
            cpu: 4000m
          requests:
            memory: 1024Mi
            cpu: 1000m
        env:
        - name: VAULT_KV_PATH
          value: VAULT_KV_PATH
        - name: IPAM_BASE
          value: "/phpipam/"
        ports:
        - containerPort: 80
        - containerPort: 443
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
      imagePullSecrets:
      - name: regcred
