---
apiVersion: v1
kind: Service
metadata:
  name: phpipam
  namespace: phpipam-dev
  labels:
    app: phpipam
spec:
  type: ClusterIP
  selector:
    app: phpipam
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
    - protocol: TCP
      port: 443
      name: https
      targetPort: 443
